//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consecutivo
    {
        public int ID_Consecutivos { get; set; }
        public string Nombre { get; set; }
        public int Valor { get; set; }
        public string Prefijo { get; set; }
    }
}
