//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        public int ID_Libro { get; set; }
        public Nullable<int> Genero_Libro { get; set; }
        public string Nombre_Libro { get; set; }
        public Nullable<int> Autor_Libro { get; set; }
        public Nullable<int> Idioma_Libro { get; set; }
        public Nullable<int> Editorial_Libro { get; set; }
        public System.DateTime Ano_Libro { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Editorial Editorial { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Idioma Idioma { get; set; }
    }
}
