//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pelicula
    {
        public int ID_Pelicula { get; set; }
        public Nullable<int> Genero_Pelicula { get; set; }
        public string Nombre_Pelicula { get; set; }
        public System.DateTime Ano_Pelicula { get; set; }
        public Nullable<int> Idioma_Pelicula { get; set; }
        public int Actor1_Pelicula { get; set; }
        public int Actor2_Pelicula { get; set; }
        public Nullable<int> Actor3_Pelicula { get; set; }
        public Nullable<int> Actor4_Pelicula { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Actor Actor1 { get; set; }
        public virtual Actor Actor2 { get; set; }
        public virtual Actor Actor3 { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual Idioma Idioma { get; set; }
    }
}
