//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Bitacora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Bitacora()
        {
            this.Bitacoras = new HashSet<Bitacora>();
        }
    
        public int Cod_Tipo_Bitacora { get; set; }
        public string Tipo_Bitacora1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora> Bitacoras { get; set; }
    }
}
