//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioWebTest2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Cod_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Pri_Ape_Usuario { get; set; }
        public string Seg_Ape_Usuario { get; set; }
        public string Email_Usuario { get; set; }
        public string Pass_Usuario { get; set; }
        public Nullable<int> Tipo_Usuario { get; set; }
    
        public virtual Tipo_Usuario Tipo_Usuario1 { get; set; }
    }
}
